global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'livekit'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          # Target options:
          # 1. 'livekit-server:7880' (if metrics container runs in the same docker network as LiveKit)
          # 2. 'host.docker.internal:7880' (for local docker setups)
          # 3. 'livekit.yourdomain.com:443' (to scrape publicly over SSL proxy)
          - 'host.docker.internal:7880'
